### ISSUE TITLE
Looses wlan0

### ISSUE THREAD

**Issue by TokenSolution** [sneakymonk3y/foxhound-nsm#7]
Installed on raspian light following sneakymonk3y's blog, after reboot I can log in but 'ls' does not list anything, ifconfig does not show wlan0 or eth0, can no longer ssh into box.

**Comment by gebhard73** [comment]
Please try my fork (some bux fixes, still in queued pull requests): https://github.com/gebhard73/foxhound-nsm and let me know if this works for you.

**Comment by TokenSolution** [comment]
It worked, thank you!  Only catch is critical stack's DNS, both your script or manually inputting sudo wget --no-check-certificate https://intel.criticalstack.com/client/critical-stack-intel-arm.deb gets a 404 Not Found.

**Comment by gebhard73** [comment]
Thanks, will have a look.

**Comment by gebhard73** [comment]
They changed the client installation - have opened an issue (#8 ). Please close this issue if everything else works fine, thank you!
